import { query } from '@/core/db/pglite'
import { randomUUID } from 'node:crypto'
function genRepo(table: string, fields: Record<string, string>) {
  return {
    async create(data: Record<string, unknown>) { const id = randomUUID(); const cols = ['id']; const vals: unknown[] = [id]; for (const [k, c] of Object.entries(fields)) { if (data[k] !== undefined && data[k] !== null) { cols.push(c); vals.push(data[k]) } } const ph = vals.map((_, i) => `\$${i + 1}`).join(', '); await query(`INSERT INTO ${table} (${cols.join(', ')}, created_at, updated_at) VALUES (${ph}, NOW(), NOW())`, vals); const r = await query(`SELECT * FROM ${table} WHERE id = $1`, [id]); return r.rows[0] ?? null },
    async findById(t: string, id: string) { const r = await query(`SELECT * FROM ${table} WHERE tenant_id = $1 AND id = $2 AND deleted_at IS NULL`, [t, id]); return r.rows[0] ?? null },
    async list(t: string, p: { page?: number; pageSize?: number; search?: string; isActive?: boolean } = {}) { const pg = p.page ?? 1; const ps = p.pageSize ?? 25; const off = (pg - 1) * ps; let w = 'tenant_id = $1 AND deleted_at IS NULL'; const sp: unknown[] = [t]; let i = 2; if (p.search) { w += ` AND (account_code ILIKE $${i} OR account_name ILIKE $${i})`; sp.push(`%${p.search}%`); i++ } if (p.isActive !== undefined) { w += ` AND is_active = $${i++}`; sp.push(p.isActive) } const c = await query<{ cnt: string }>(`SELECT COUNT(*) as cnt FROM ${table} WHERE ${w}`, sp); const r = await query(`SELECT * FROM ${table} WHERE ${w} ORDER BY created_at DESC LIMIT $${i} OFFSET $${i + 1}`, [...sp, ps, off]); return { rows: r.rows, total: Number(c.rows[0]!.cnt), page: pg, pageSize: ps } },
  }
}
export const chartOfAccountsRepository = genRepo('chart_of_accounts', { tenantId: 'tenant_id', accountCode: 'account_code', accountName: 'account_name', accountType: 'account_type', accountSubtype: 'account_subtype', parentAccountId: 'parent_account_id', level: 'level', isActive: 'is_active', isPostable: 'is_postable', openingBalance: 'opening_balance', currentBalance: 'current_balance', currency: 'currency', costCenterRequired: 'cost_center_required', description: 'description' })
export const fiscalYearRepository = genRepo('fiscal_years', { tenantId: 'tenant_id', fiscalYear: 'fiscal_year', startDate: 'start_date', endDate: 'end_date', isCurrent: 'is_current', isClosed: 'is_closed', closedAt: 'closed_at', closedBy: 'closed_by', closedByName: 'closed_by_name', description: 'description' })
export const fiscalPeriodRepository = genRepo('fiscal_periods', { tenantId: 'tenant_id', fiscalYearId: 'fiscal_year_id', fiscalYear: 'fiscal_year', periodNumber: 'period_number', periodName: 'period_name', startDate: 'start_date', endDate: 'end_date', status: 'status', isAdjustmentPeriod: 'is_adjustment_period', closedAt: 'closed_at', closedBy: 'closed_by', closedByName: 'closed_by_name' })
export const costCenterRepository = genRepo('cost_centers', { tenantId: 'tenant_id', ccCode: 'cc_code', ccName: 'cc_name', parentCcId: 'parent_cc_id', companyId: 'company_id', companyName: 'company_name', plantId: 'plant_id', plantName: 'plant_name', departmentId: 'department_id', isActive: 'is_active', description: 'description' })
export const profitCenterRepository = genRepo('profit_centers', { tenantId: 'tenant_id', pcCode: 'pc_code', pcName: 'pc_name', parentPcId: 'parent_pc_id', companyId: 'company_id', companyName: 'company_name', isActive: 'is_active', description: 'description' })
export const currencyRepository = genRepo('currencies', { tenantId: 'tenant_id', currencyCode: 'currency_code', currencyName: 'currency_name', symbol: 'symbol', decimalPlaces: 'decimal_places', isBaseCurrency: 'is_base_currency', isActive: 'is_active' })
export const exchangeRateRepository = genRepo('exchange_rates', { tenantId: 'tenant_id', fromCurrency: 'from_currency', toCurrency: 'to_currency', rate: 'rate', rateDate: 'rate_date', rateType: 'rate_type' })
