/** Pricing Engine API Routes */
import { Hono } from 'hono'
import { z } from 'zod'
import { zValidator } from '@hono/zod-validator'
import { success, paginated } from '@/core/response'
import { requirePermission } from '@/middleware/rbac'
import { Permission } from '@/core/permissions'
import { pricingEngineService } from '../service'

export const pricingEngineRoutes = new Hono()
const CR = Permission.PRICING_READ
const CU = Permission.PRICING_CREATE

const plSchema = z.object({ listCode: z.string().min(1), listName: z.string().min(1), listType: z.string().default('STANDARD'), channel: z.string().optional(), currency: z.string().default('INR'), effectiveFrom: z.string(), effectiveTo: z.string().optional(), description: z.string().optional() })
const promoSchema = z.object({ promoCode: z.string().min(1), promoName: z.string().min(1), promoType: z.string().min(1), scope: z.string().default('PRODUCT'), productId: z.string().uuid().optional(), productCategoryId: z.string().uuid().optional(), customerId: z.string().uuid().optional(), discountType: z.string().min(1), discountValue: z.number().positive(), minQty: z.number().positive().optional(), maxQty: z.number().positive().optional(), minOrderValue: z.number().positive().optional(), maxDiscountAmount: z.number().positive().optional(), buyQty: z.number().positive().optional(), getQty: z.number().positive().optional(), startDate: z.string(), endDate: z.string(), usageLimit: z.number().int().positive().optional(), description: z.string().optional(), termsConditions: z.string().optional() })
const couponSchema = z.object({ couponCode: z.string().min(1), couponName: z.string().min(1), couponType: z.string().min(1), discountType: z.string().min(1), discountValue: z.number().positive(), minOrderValue: z.number().positive().optional(), maxDiscountAmount: z.number().positive().optional(), startDate: z.string(), endDate: z.string(), usageLimit: z.number().int().positive().default(1), perCustomerLimit: z.number().int().positive().default(1), description: z.string().optional() })
const taxSchema = z.object({ taxCode: z.string().min(1), taxName: z.string().min(1), taxType: z.string().min(1), taxPercent: z.number().min(0).max(100), hsnCode: z.string().optional(), sacCode: z.string().optional(), isReverseCharge: z.boolean().default(false), description: z.string().optional() })
const calcSchema = z.object({ productId: z.string().uuid(), customerId: z.string().uuid().optional(), channel: z.string().optional(), quantity: z.number().positive(), uomCode: z.string().min(1), couponCode: z.string().optional() })

pricingEngineRoutes.get('/price-lists', requirePermission(CR), async (c) => { const r = await pricingEngineService.listPriceLists({ page: Number(c.req.query('page') ?? 1), pageSize: Number(c.req.query('pageSize') ?? 25), search: c.req.query('search') ?? undefined, isActive: c.req.query('isActive') === 'true' ? true : c.req.query('isActive') === 'false' ? false : undefined }); return c.json(paginated(r.rows, { correlationId: c.req.header('X-Request-Id') ?? '', page: r.page, pageSize: r.pageSize, total: r.total })) })
pricingEngineRoutes.post('/price-lists', requirePermission(CU), zValidator('json', plSchema), async (c) => { const b = c.req.valid('json' as never) as z.infer<typeof plSchema>; const pl = await pricingEngineService.createPriceList(b); return c.json(success(pl, { message: 'Price list created' }), 201) })
pricingEngineRoutes.get('/promotions', requirePermission(CR), async (c) => { const r = await pricingEngineService.listPromotions({ page: Number(c.req.query('page') ?? 1), pageSize: Number(c.req.query('pageSize') ?? 25), search: c.req.query('search') ?? undefined, isActive: c.req.query('isActive') === 'true' ? true : c.req.query('isActive') === 'false' ? false : undefined }); return c.json(paginated(r.rows, { correlationId: c.req.header('X-Request-Id') ?? '', page: r.page, pageSize: r.pageSize, total: r.total })) })
pricingEngineRoutes.post('/promotions', requirePermission(CU), zValidator('json', promoSchema), async (c) => { const b = c.req.valid('json' as never) as z.infer<typeof promoSchema>; const p = await pricingEngineService.createPromotion(b); return c.json(success(p, { message: 'Promotion created' }), 201) })
pricingEngineRoutes.get('/coupons', requirePermission(CR), async (c) => { const r = await pricingEngineService.listCoupons({ page: Number(c.req.query('page') ?? 1), pageSize: Number(c.req.query('pageSize') ?? 25), search: c.req.query('search') ?? undefined, isActive: c.req.query('isActive') === 'true' ? true : c.req.query('isActive') === 'false' ? false : undefined }); return c.json(paginated(r.rows, { correlationId: c.req.header('X-Request-Id') ?? '', page: r.page, pageSize: r.pageSize, total: r.total })) })
pricingEngineRoutes.post('/coupons', requirePermission(CU), zValidator('json', couponSchema), async (c) => { const b = c.req.valid('json' as never) as z.infer<typeof couponSchema>; const cp = await pricingEngineService.createCoupon(b); return c.json(success(cp, { message: 'Coupon created' }), 201) })
pricingEngineRoutes.post('/calculate', requirePermission(CR), zValidator('json', calcSchema), async (c) => { const b = c.req.valid('json' as never) as z.infer<typeof calcSchema>; const r = await pricingEngineService.calculatePrice(b); return c.json(success(r)) })
pricingEngineRoutes.get('/tax-configs', requirePermission(CR), async (c) => { const r = await pricingEngineService.listTaxConfigs({ page: Number(c.req.query('page') ?? 1), pageSize: Number(c.req.query('pageSize') ?? 25), search: c.req.query('search') ?? undefined, isActive: c.req.query('isActive') === 'true' ? true : c.req.query('isActive') === 'false' ? false : undefined }); return c.json(paginated(r.rows, { correlationId: c.req.header('X-Request-Id') ?? '', page: r.page, pageSize: r.pageSize, total: r.total })) })
pricingEngineRoutes.post('/tax-configs', requirePermission(CU), zValidator('json', taxSchema), async (c) => { const b = c.req.valid('json' as never) as z.infer<typeof taxSchema>; const t = await pricingEngineService.createTaxConfig(b); return c.json(success(t, { message: 'Tax config created' }), 201) })
