/**
 * @suop/backend — Error Code Catalog
 *
 * Per API Standards §10: All error codes are namespaced strings:
 *   <DOMAIN>.<ENTITY>.<RULE>
 *
 * This file is the single source of truth. No code may use an error code
 * that is not declared here.
 */

export const ErrorCode = {
  // ─── Validation ──────────────────────────────────────
  VALIDATION_REQUIRED_FIELD: 'VALIDATION.REQUIRED_FIELD',
  VALIDATION_INVALID_FORMAT: 'VALIDATION.INVALID_FORMAT',
  VALIDATION_OUT_OF_RANGE: 'VALIDATION.OUT_OF_RANGE',
  VALIDATION_INVALID_ENUM: 'VALIDATION.INVALID_ENUM',
  VALIDATION_BUSINESS_RULE: 'VALIDATION.BUSINESS_RULE',

  // ─── Auth ────────────────────────────────────────────
  AUTH_TOKEN_EXPIRED: 'AUTH.TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH.TOKEN_INVALID',
  AUTH_TOKEN_MISSING: 'AUTH.TOKEN_MISSING',
  AUTH_INVALID_CREDENTIALS: 'AUTH.INVALID_CREDENTIALS',
  AUTH_ACCOUNT_LOCKED: 'AUTH.ACCOUNT_LOCKED',
  AUTH_ACCOUNT_DISABLED: 'AUTH.ACCOUNT_DISABLED',
  AUTH_MFA_REQUIRED: 'AUTH.MFA_REQUIRED',
  AUTH_MFA_INVALID: 'AUTH.MFA_INVALID',
  AUTH_REFRESH_TOKEN_INVALID: 'AUTH.REFRESH_TOKEN_INVALID',
  AUTH_REFRESH_TOKEN_EXPIRED: 'AUTH.REFRESH_TOKEN_EXPIRED',
  AUTH_REFRESH_TOKEN_REPLAY: 'AUTH.REFRESH_TOKEN_REPLAY',

  // ─── RBAC ────────────────────────────────────────────
  RBAC_PERMISSION_DENIED: 'RBAC.PERMISSION_DENIED',
  RBAC_TENANT_MISMATCH: 'RBAC.TENANT_MISMATCH',

  // ─── Concurrency ─────────────────────────────────────
  CONCURRENCY_VERSION_MISMATCH: 'CONCURRENCY.VERSION_MISMATCH',
  CONCURRENCY_DEADLOCK_RETRY: 'CONCURRENCY.DEADLOCK_RETRY',

  // ─── General ─────────────────────────────────────────
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  // ─── External ────────────────────────────────────────
  EXTERNAL_S3_UNAVAILABLE: 'EXTERNAL.S3_UNAVAILABLE',
  EXTERNAL_EMAIL_SEND_FAILED: 'EXTERNAL.EMAIL_SEND_FAILED',
  EXTERNAL_REDIS_UNAVAILABLE: 'EXTERNAL.REDIS_UNAVAILABLE',

  // ─── Database ────────────────────────────────────────
  DATABASE_CONNECTION_FAILED: 'DATABASE.CONNECTION_FAILED',
  DATABASE_TRANSACTION_FAILED: 'DATABASE.TRANSACTION_FAILED',
} as const

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode]

/** HTTP status code mapping for each error code */
export const ERROR_HTTP_STATUS: Record<string, number> = {
  [ErrorCode.VALIDATION_REQUIRED_FIELD]: 400,
  [ErrorCode.VALIDATION_INVALID_FORMAT]: 400,
  [ErrorCode.VALIDATION_OUT_OF_RANGE]: 400,
  [ErrorCode.VALIDATION_INVALID_ENUM]: 400,
  [ErrorCode.VALIDATION_BUSINESS_RULE]: 422,
  [ErrorCode.AUTH_TOKEN_EXPIRED]: 401,
  [ErrorCode.AUTH_TOKEN_INVALID]: 401,
  [ErrorCode.AUTH_TOKEN_MISSING]: 401,
  [ErrorCode.AUTH_INVALID_CREDENTIALS]: 401,
  [ErrorCode.AUTH_ACCOUNT_LOCKED]: 423,
  [ErrorCode.AUTH_ACCOUNT_DISABLED]: 403,
  [ErrorCode.AUTH_MFA_REQUIRED]: 401,
  [ErrorCode.AUTH_MFA_INVALID]: 401,
  [ErrorCode.AUTH_REFRESH_TOKEN_INVALID]: 401,
  [ErrorCode.AUTH_REFRESH_TOKEN_EXPIRED]: 401,
  [ErrorCode.AUTH_REFRESH_TOKEN_REPLAY]: 401,
  [ErrorCode.RBAC_PERMISSION_DENIED]: 403,
  [ErrorCode.RBAC_TENANT_MISMATCH]: 403,
  [ErrorCode.CONCURRENCY_VERSION_MISMATCH]: 409,
  [ErrorCode.CONCURRENCY_DEADLOCK_RETRY]: 409,
  [ErrorCode.NOT_FOUND]: 404,
  [ErrorCode.CONFLICT]: 409,
  [ErrorCode.RATE_LIMIT_EXCEEDED]: 429,
  [ErrorCode.SERVICE_UNAVAILABLE]: 503,
  [ErrorCode.INTERNAL_ERROR]: 500,
  [ErrorCode.EXTERNAL_S3_UNAVAILABLE]: 502,
  [ErrorCode.EXTERNAL_EMAIL_SEND_FAILED]: 502,
  [ErrorCode.EXTERNAL_REDIS_UNAVAILABLE]: 502,
  [ErrorCode.DATABASE_CONNECTION_FAILED]: 503,
  [ErrorCode.DATABASE_TRANSACTION_FAILED]: 500,
}
