import { query } from '@/core/db/pglite'
import { randomUUID } from 'node:crypto'
function genRepo(table: string, fields: Record<string, string>) {
  return {
    async create(data: Record<string, unknown>) { const id = randomUUID(); const cols = ['id']; const vals: unknown[] = [id]; for (const [k, c] of Object.entries(fields)) { if (data[k] !== undefined && data[k] !== null) { cols.push(c); vals.push(data[k]) } } const ph = vals.map((_, i) => `\$${i + 1}`).join(', '); await query(`INSERT INTO ${table} (${cols.join(', ')}, created_at, updated_at) VALUES (${ph}, NOW(), NOW())`, vals); const r = await query(`SELECT * FROM ${table} WHERE id = $1`, [id]); return r.rows[0] ?? null },
    async findById(t: string, id: string) { const r = await query(`SELECT * FROM ${table} WHERE tenant_id = $1 AND id = $2 AND deleted_at IS NULL`, [t, id]); return r.rows[0] ?? null },
    async list(t: string, p: { page?: number; pageSize?: number; status?: string } = {}) { const pg = p.page ?? 1; const ps = p.pageSize ?? 25; const off = (pg - 1) * ps; let w = 'tenant_id = $1 AND deleted_at IS NULL'; const sp: unknown[] = [t]; let i = 2; if (p.status) { w += ` AND status = $${i++}`; sp.push(p.status) } const c = await query<{ cnt: string }>(`SELECT COUNT(*) as cnt FROM ${table} WHERE ${w}`, sp); const r = await query(`SELECT * FROM ${table} WHERE ${w} ORDER BY created_at DESC LIMIT $${i} OFFSET $${i + 1}`, [...sp, ps, off]); return { rows: r.rows, total: Number(c.rows[0]!.cnt), page: pg, pageSize: ps } },
  }
}
export const rmaRepository = genRepo('rma_requests', { tenantId: 'tenant_id', rmaNumber: 'rma_number', soId: 'so_id', soNumber: 'so_number', deliveryOrderId: 'delivery_order_id', deliveryNumber: 'delivery_number', customerId: 'customer_id', customerCode: 'customer_code', customerName: 'customer_name', returnType: 'return_type', returnReason: 'return_reason', returnReasonDetail: 'return_reason_detail', totalQty: 'total_qty', totalValue: 'total_value', currency: 'currency', isApproved: 'is_approved', approvedBy: 'approved_by', approvedByName: 'approved_by_name', approvedAt: 'approved_at', approvalNotes: 'approval_notes', rejectionReason: 'rejection_reason', status: 'status', remarks: 'remarks' })
export const rmaLineRepository = genRepo('rma_lines', { tenantId: 'tenant_id', rmaId: 'rma_id', lineNo: 'line_no', soLineId: 'so_line_id', productId: 'product_id', productSku: 'product_sku', productName: 'product_name', uomId: 'uom_id', uomCode: 'uom_code', shippedQty: 'shipped_qty', returnedQty: 'returned_qty', acceptedQty: 'accepted_qty', rejectedQty: 'rejected_qty', batchId: 'batch_id', batchNumber: 'batch_number', lotId: 'lot_id', lotNumber: 'lot_number', unitPrice: 'unit_price', lineTotal: 'line_total', returnReason: 'return_reason', condition: 'condition', disposition: 'disposition', inspectionStatus: 'inspection_status', remarks: 'remarks' })
export const returnInspectionRepository = genRepo('return_inspections', { tenantId: 'tenant_id', rmaId: 'rma_id', rmaNumber: 'rma_number', rmaLineId: 'rma_line_id', inspectorId: 'inspector_id', inspectorName: 'inspector_name', receivedQty: 'received_qty', acceptedQty: 'accepted_qty', rejectedQty: 'rejected_qty', scrapQty: 'scrap_qty', repairQty: 'repair_qty', inspectionResult: 'inspection_result', disposition: 'disposition', qualityHold: 'quality_hold', holdReason: 'hold_reason', remarks: 'remarks' })
export const refundRepository = genRepo('refund_records', { tenantId: 'tenant_id', refundNumber: 'refund_number', rmaId: 'rma_id', rmaNumber: 'rma_number', customerId: 'customer_id', customerName: 'customer_name', originalInvoiceNumber: 'original_invoice_number', refundAmount: 'refund_amount', currency: 'currency', refundType: 'refund_type', refundMethod: 'refund_method', status: 'status', approvedBy: 'approved_by', approvedByName: 'approved_by_name', approvedAt: 'approved_at', processedBy: 'processed_by', processedByName: 'processed_by_name', processedAt: 'processed_at', referenceNumber: 'reference_number', remarks: 'remarks' })
export async function genRmaNumber(t: string): Promise<string> { const y = new Date().getFullYear(); const c = await query<{ cnt: string }>(`SELECT COUNT(*) as cnt FROM rma_requests WHERE tenant_id = $1 AND rma_number LIKE 'RMA-${y}-%'`, [t]); return `RMA-${y}-${String(Number(c.rows[0]!.cnt) + 1).padStart(6, '0')}` }
export async function genRefundNumber(t: string): Promise<string> { const y = new Date().getFullYear(); const c = await query<{ cnt: string }>(`SELECT COUNT(*) as cnt FROM refund_records WHERE tenant_id = $1 AND refund_number LIKE 'REF-${y}-%'`, [t]); return `REF-${y}-${String(Number(c.rows[0]!.cnt) + 1).padStart(6, '0')}` }
