import { Hono } from 'hono'
import { z } from 'zod'
import { zValidator } from '@hono/zod-validator'
import { success, paginated } from '@/core/response'
import { requirePermission } from '@/middleware/rbac'
import { Permission } from '@/core/permissions'
import { financialFoundationService } from '../service'
export const financialFoundationRoutes = new Hono()
const FR = Permission.FINANCE_READ; const FU = Permission.FINANCE_CREATE // Finance read/update proxy
const accSchema = z.object({ accountCode: z.string().min(1), accountName: z.string().min(1), accountType: z.enum(['ASSET', 'LIABILITY', 'EQUITY', 'REVENUE', 'EXPENSE', 'COGS']), accountSubtype: z.string().optional(), parentAccountId: z.string().uuid().optional(), isPostable: z.boolean().default(true), openingBalance: z.number().default(0), currency: z.string().default('INR'), description: z.string().optional() })
const fySchema = z.object({ fiscalYear: z.string().min(1), startDate: z.string(), endDate: z.string(), description: z.string().optional() })
const ccSchema = z.object({ ccCode: z.string().min(1), ccName: z.string().min(1), parentCcId: z.string().uuid().optional(), companyId: z.string().uuid().optional(), companyName: z.string().optional(), plantId: z.string().uuid().optional(), plantName: z.string().optional(), description: z.string().optional() })
const pcSchema = z.object({ pcCode: z.string().min(1), pcName: z.string().min(1), parentPcId: z.string().uuid().optional(), companyId: z.string().uuid().optional(), companyName: z.string().optional(), description: z.string().optional() })
const currSchema = z.object({ currencyCode: z.string().min(1), currencyName: z.string().min(1), symbol: z.string().optional(), decimalPlaces: z.number().int().default(2), isBaseCurrency: z.boolean().default(false) })
const erSchema = z.object({ fromCurrency: z.string().min(1), toCurrency: z.string().min(1), rate: z.number().positive(), rateDate: z.string(), rateType: z.string().default('DAILY') })
financialFoundationRoutes.get('/accounts', requirePermission(FR), async (c) => { const r = await financialFoundationService.listAccounts({ page: Number(c.req.query('page') ?? 1), pageSize: Number(c.req.query('pageSize') ?? 25), search: c.req.query('search') ?? undefined, isActive: c.req.query('isActive') === 'true' ? true : c.req.query('isActive') === 'false' ? false : undefined }); return c.json(paginated(r.rows, { correlationId: c.req.header('X-Request-Id') ?? '', page: r.page, pageSize: r.pageSize, total: r.total })) })
financialFoundationRoutes.post('/accounts', requirePermission(FU), zValidator('json', accSchema), async (c) => { const b = c.req.valid('json' as never) as z.infer<typeof accSchema>; const a = await financialFoundationService.createAccount(b); return c.json(success(a, { message: 'Account created' }), 201) })
financialFoundationRoutes.get('/fiscal-years', requirePermission(FR), async (c) => { const r = await financialFoundationService.listFiscalYears({ page: Number(c.req.query('page') ?? 1), pageSize: Number(c.req.query('pageSize') ?? 25) }); return c.json(paginated(r.rows, { correlationId: c.req.header('X-Request-Id') ?? '', page: r.page, pageSize: r.pageSize, total: r.total })) })
financialFoundationRoutes.post('/fiscal-years', requirePermission(FU), zValidator('json', fySchema), async (c) => { const b = c.req.valid('json' as never) as z.infer<typeof fySchema>; const f = await financialFoundationService.createFiscalYear(b); return c.json(success(f, { message: 'Fiscal year created' }), 201) })
financialFoundationRoutes.get('/fiscal-periods', requirePermission(FR), async (c) => { const r = await financialFoundationService.listFiscalPeriods({ page: Number(c.req.query('page') ?? 1), pageSize: Number(c.req.query('pageSize') ?? 25) }); return c.json(paginated(r.rows, { correlationId: c.req.header('X-Request-Id') ?? '', page: r.page, pageSize: r.pageSize, total: r.total })) })
financialFoundationRoutes.post('/fiscal-periods/close', requirePermission(FU), async (c) => { const b = await c.req.json(); const r = await financialFoundationService.closePeriod(b); return c.json(success(r, { message: 'Period closed' })) })
financialFoundationRoutes.get('/cost-centers', requirePermission(FR), async (c) => { const r = await financialFoundationService.listCostCenters({ page: Number(c.req.query('page') ?? 1), pageSize: Number(c.req.query('pageSize') ?? 25), search: c.req.query('search') ?? undefined, isActive: c.req.query('isActive') === 'true' ? true : c.req.query('isActive') === 'false' ? false : undefined }); return c.json(paginated(r.rows, { correlationId: c.req.header('X-Request-Id') ?? '', page: r.page, pageSize: r.pageSize, total: r.total })) })
financialFoundationRoutes.post('/cost-centers', requirePermission(FU), zValidator('json', ccSchema), async (c) => { const b = c.req.valid('json' as never) as z.infer<typeof ccSchema>; const cc = await financialFoundationService.createCostCenter(b); return c.json(success(cc, { message: 'Cost center created' }), 201) })
financialFoundationRoutes.get('/profit-centers', requirePermission(FR), async (c) => { const r = await financialFoundationService.listProfitCenters({ page: Number(c.req.query('page') ?? 1), pageSize: Number(c.req.query('pageSize') ?? 25), search: c.req.query('search') ?? undefined, isActive: c.req.query('isActive') === 'true' ? true : c.req.query('isActive') === 'false' ? false : undefined }); return c.json(paginated(r.rows, { correlationId: c.req.header('X-Request-Id') ?? '', page: r.page, pageSize: r.pageSize, total: r.total })) })
financialFoundationRoutes.post('/profit-centers', requirePermission(FU), zValidator('json', pcSchema), async (c) => { const b = c.req.valid('json' as never) as z.infer<typeof pcSchema>; const pc = await financialFoundationService.createProfitCenter(b); return c.json(success(pc, { message: 'Profit center created' }), 201) })
financialFoundationRoutes.get('/currencies', requirePermission(FR), async (c) => { const r = await financialFoundationService.listCurrencies({ page: Number(c.req.query('page') ?? 1), pageSize: Number(c.req.query('pageSize') ?? 25), search: c.req.query('search') ?? undefined, isActive: c.req.query('isActive') === 'true' ? true : c.req.query('isActive') === 'false' ? false : undefined }); return c.json(paginated(r.rows, { correlationId: c.req.header('X-Request-Id') ?? '', page: r.page, pageSize: r.pageSize, total: r.total })) })
financialFoundationRoutes.post('/currencies', requirePermission(FU), zValidator('json', currSchema), async (c) => { const b = c.req.valid('json' as never) as z.infer<typeof currSchema>; const cu = await financialFoundationService.createCurrency(b); return c.json(success(cu, { message: 'Currency created' }), 201) })
financialFoundationRoutes.get('/exchange-rates', requirePermission(FR), async (c) => { const r = await financialFoundationService.listExchangeRates({ page: Number(c.req.query('page') ?? 1), pageSize: Number(c.req.query('pageSize') ?? 25) }); return c.json(paginated(r.rows, { correlationId: c.req.header('X-Request-Id') ?? '', page: r.page, pageSize: r.pageSize, total: r.total })) })
financialFoundationRoutes.post('/exchange-rates', requirePermission(FU), zValidator('json', erSchema), async (c) => { const b = c.req.valid('json' as never) as z.infer<typeof erSchema>; const er = await financialFoundationService.setExchangeRate(b); return c.json(success(er, { message: 'Exchange rate set' }), 201) })
