/**
 * Section 04 — Operations & WMS
 * Public API barrel — re-exports all 38 extracted module components.
 * page.tsx imports from here instead of defining them inline.
 */

export { InventoryModule } from './components/inventory'
export { GoodsReceiptModule } from './components/goods-receipt'
export { StockIssueModule } from './components/stock-issue'
export { StockTransferModule } from './components/stock-transfer'
export { AdjustmentModule } from './components/adjustment'
export { ReservationModule } from './components/reservation'
export { CycleCountModule } from './components/cycle-count'
export { BatchExpiryModule } from './components/batch-expiry'
export { CostingModule } from './components/costing'
export { MissionControlModule } from './components/mission-control'
export { ReceivingModule } from './components/receiving'
export { PutawayModule } from './components/putaway'
export { FulfillmentModule } from './components/fulfillment'
export { DispatchModule } from './components/dispatch'
export { WavePlanningModule } from './components/wave-planning'
export { TaskQueueModule } from './components/task-queue'
export { WorkforceModule } from './components/workforce'
export { EquipmentModule } from './components/equipment'
export { ControlTowerModule } from './components/control-tower'
export { SLADashboardModule } from './components/sla-dashboard'
export { ExceptionCenterModule } from './components/exception-center'
export { WorkforceAnalyticsModule } from './components/workforce-analytics'
export { CrossDockConsoleModule } from './components/cross-dock-console'
export { TruckQueueModule } from './components/truck-queue'
export { DockScheduleModule } from './components/dock-schedule'
export { YardMapModule } from './components/yard-map'
export { VehicleTrackerModule } from './components/vehicle-tracker'
export { GateConsoleModule } from './components/gate-console'
export { YardControlTowerModule } from './components/yard-control-tower'
export { CrossDockAnalyticsModule } from './components/cross-dock-analytics'
export { EquipmentMasterModule } from './components/equipment-master'
export { ForkliftDashboardModule } from './components/forklift-dashboard'
export { ScannerManagementModule } from './components/scanner-management'
export { BatteryDashboardModule } from './components/battery-dashboard'
export { MaintenancePlannerModule } from './components/maintenance-planner'
export { BreakdownConsoleModule } from './components/breakdown-console'
export { CertificationCenterModule } from './components/certification-center'
export { EquipmentAnalyticsModule } from './components/equipment-analytics'
