// Backward compat shim — all clients moved to @/api
export { pricingApi } from '@/api/sales'
export { gstApi } from '@/api/finance'
export { financeApi, financeFoundationApi } from '@/api/finance'
export { costingApi } from '@/api/finance'
export { productApi, catalogApi } from '@/api/catalog'
export { customerApi } from '@/api/partners'
export { supplierApi } from '@/api/partners'
export { inventoryApi } from '@/api/inventory'
export { warehouseApi } from '@/api/warehouse'
export { goodsReceiptApi } from '@/api/warehouse'
export { organizationApi, companyApi, plantApi, orgWarehouseApi, departmentApi, costCenterApi, financialYearApi, hierarchyApi } from '@/api/organization'
export { useAuthStore } from '@/stores/auth-store'
