import { Hono } from 'hono'
import { z } from 'zod'
import { zValidator } from '@hono/zod-validator'
import { success, paginated } from '@/core/response'
import { requirePermission } from '@/middleware/rbac'
import { Permission } from '@/core/permissions'
import { customerReturnsService } from '../service'
export const customerReturnsRoutes = new Hono()
const CR = Permission.RETURNS_READ
const CU = Permission.RETURNS_CREATE
const rmaSchema = z.object({ soId: z.string().uuid().optional(), soNumber: z.string().optional(), deliveryOrderId: z.string().uuid().optional(), deliveryNumber: z.string().optional(), customerId: z.string().uuid(), customerCode: z.string().optional(), customerName: z.string().min(1), returnType: z.enum(['DAMAGE', 'DEFECTIVE', 'WRONG_ITEM', 'EXPIRED', 'NOT_REQUIRED', 'QUALITY_ISSUE']).default('DAMAGE'), returnReason: z.string().min(1), returnReasonDetail: z.string().optional(), lines: z.array(z.object({ productId: z.string().uuid(), productSku: z.string().min(1), productName: z.string().min(1), uomCode: z.string().min(1), shippedQty: z.number().positive(), returnedQty: z.number().positive(), unitPrice: z.number().nonnegative(), batchNumber: z.string().optional(), lotNumber: z.string().optional(), returnReason: z.string().optional(), condition: z.enum(['GOOD', 'DAMAGED', 'DEFECTIVE']).default('GOOD') })).min(1) })
const rmaTransitionSchema = z.object({ targetStatus: z.enum(['REQUESTED', 'APPROVED', 'REJECTED', 'RETURN_RECEIVED', 'INSPECTION_PENDING', 'INSPECTED', 'RESOLVED', 'CLOSED']), version: z.number().int().min(0) })
const inspSchema = z.object({ rmaLineId: z.string().uuid().optional(), receivedQty: z.number().positive(), acceptedQty: z.number().nonnegative().default(0), rejectedQty: z.number().nonnegative().default(0), scrapQty: z.number().nonnegative().default(0), repairQty: z.number().nonnegative().default(0), inspectionResult: z.string().default('ACCEPTED'), disposition: z.enum(['RETURN_TO_STOCK', 'SCRAP', 'REPAIR', 'REJECT', 'HOLD']).default('RETURN_TO_STOCK'), qualityHold: z.boolean().default(false), holdReason: z.string().optional(), remarks: z.string().optional() })
const refundSchema = z.object({ rmaId: z.string().uuid(), rmaNumber: z.string().optional(), customerId: z.string().uuid().optional(), customerName: z.string().optional(), originalInvoiceNumber: z.string().optional(), refundAmount: z.number().positive(), currency: z.string().default('INR'), refundType: z.enum(['CREDIT_NOTE', 'CASH_REFUND', 'BANK_TRANSFER', 'ADJUSTMENT']).default('CREDIT_NOTE'), refundMethod: z.string().optional(), remarks: z.string().optional() })
customerReturnsRoutes.get('/rmas', requirePermission(CR), async (c) => { const r = await customerReturnsService.list({ page: Number(c.req.query('page') ?? 1), pageSize: Number(c.req.query('pageSize') ?? 25), status: c.req.query('status') ?? undefined }); return c.json(paginated(r.rows, { correlationId: c.req.header('X-Request-Id') ?? '', page: r.page, pageSize: r.pageSize, total: r.total })) })
customerReturnsRoutes.get('/rmas/:id', requirePermission(CR), async (c) => { const r = await customerReturnsService.getById(c.req.param('id')!); return c.json(success(r)) })
customerReturnsRoutes.post('/rmas', requirePermission(CU), zValidator('json', rmaSchema), async (c) => { const b = c.req.valid('json' as never) as z.infer<typeof rmaSchema>; const r = await customerReturnsService.createRma(b); return c.json(success(r, { message: 'RMA created' }), 201) })
customerReturnsRoutes.post('/rmas/:id/transition', requirePermission(CU), zValidator('json', rmaTransitionSchema), async (c) => { const b = c.req.valid('json' as never) as z.infer<typeof rmaTransitionSchema>; const r = await customerReturnsService.transition(c.req.param('id')!, b.targetStatus, b.version); return c.json(success(r, { message: `RMA transitioned to ${b.targetStatus}` })) })
customerReturnsRoutes.get('/rmas/:id/inspections', requirePermission(CR), async (c) => { const r = await customerReturnsService.listInspections(c.req.param('id')!); return c.json(success(r)) })
customerReturnsRoutes.post('/rmas/:id/inspections', requirePermission(CU), zValidator('json', inspSchema), async (c) => { const b = c.req.valid('json' as never) as z.infer<typeof inspSchema>; const r = await customerReturnsService.createInspection(c.req.param('id')!, b); return c.json(success(r, { message: 'Return inspection recorded' }), 201) })
customerReturnsRoutes.get('/refunds', requirePermission(CR), async (c) => { const r = await customerReturnsService.listRefunds({ page: Number(c.req.query('page') ?? 1), pageSize: Number(c.req.query('pageSize') ?? 25), status: c.req.query('status') ?? undefined }); return c.json(paginated(r.rows, { correlationId: c.req.header('X-Request-Id') ?? '', page: r.page, pageSize: r.pageSize, total: r.total })) })
customerReturnsRoutes.post('/refunds', requirePermission(CU), zValidator('json', refundSchema), async (c) => { const b = c.req.valid('json' as never) as z.infer<typeof refundSchema>; const r = await customerReturnsService.createRefund(b); return c.json(success(r, { message: 'Refund created' }), 201) })
