/** Frontend API Layer — SINGLE SOURCE OF TRUTH for all API clients */
export * from './core'
export * from './administration'
export * from './catalog'
export * from './partners'
export * from './organization'
export * from './inventory'
export * from './warehouse'
export * from './procurement'
export * from './sales'
export * from './manufacturing'
export * from './quality'
export * from './finance'
export * from './hr'
export * from './crm'
export * from './bi'
