import { query } from '@/core/db/pglite'
import { randomUUID } from 'node:crypto'
function genRepo(table: string, fields: Record<string, string>) {
  return {
    async create(data: Record<string, unknown>) { const id = randomUUID(); const cols = ['id']; const vals: unknown[] = [id]; for (const [k, c] of Object.entries(fields)) { if (data[k] !== undefined && data[k] !== null) { cols.push(c); vals.push(data[k]) } } const ph = vals.map((_, i) => `\$${i + 1}`).join(', '); await query(`INSERT INTO ${table} (${cols.join(', ')}, created_at, updated_at) VALUES (${ph}, NOW(), NOW())`, vals); const r = await query(`SELECT * FROM ${table} WHERE id = $1`, [id]); return r.rows[0] ?? null },
    async findById(t: string, id: string) { const r = await query(`SELECT * FROM ${table} WHERE tenant_id = $1 AND id = $2 AND deleted_at IS NULL`, [t, id]); return r.rows[0] ?? null },
    async list(t: string, p: { page?: number; pageSize?: number; status?: string } = {}) { const pg = p.page ?? 1; const ps = p.pageSize ?? 25; const off = (pg - 1) * ps; let w = 'tenant_id = $1 AND deleted_at IS NULL'; const sp: unknown[] = [t]; let i = 2; if (p.status) { w += ` AND status = $${i++}`; sp.push(p.status) } const c = await query<{ cnt: string }>(`SELECT COUNT(*) as cnt FROM ${table} WHERE ${w}`, sp); const r = await query(`SELECT * FROM ${table} WHERE ${w} ORDER BY created_at DESC LIMIT $${i} OFFSET $${i + 1}`, [...sp, ps, off]); return { rows: r.rows, total: Number(c.rows[0]!.cnt), page: pg, pageSize: ps } },
  }
}
export const pickListRepository = genRepo('pick_lists', { tenantId: 'tenant_id', pickNumber: 'pick_number', waveId: 'wave_id', waveNumber: 'wave_number', warehouseId: 'warehouse_id', warehouseName: 'warehouse_name', pickerId: 'picker_id', pickerName: 'picker_name', totalLines: 'total_lines', totalQty: 'total_qty', pickedQty: 'picked_qty', shortQty: 'short_qty', pickRoute: 'pick_route', pickStrategy: 'pick_strategy', status: 'status', startedAt: 'started_at', completedAt: 'completed_at', remarks: 'remarks' })
export const packingListRepository = genRepo('packing_lists', { tenantId: 'tenant_id', packingNumber: 'packing_number', pickListId: 'pick_list_id', pickNumber: 'pick_number', warehouseId: 'warehouse_id', warehouseName: 'warehouse_name', packerId: 'packer_id', packerName: 'packer_name', totalLines: 'total_lines', totalQty: 'total_qty', packedQty: 'packed_qty', totalWeight: 'total_weight', totalVolume: 'total_volume', boxCount: 'box_count', status: 'status', startedAt: 'started_at', completedAt: 'completed_at', remarks: 'remarks' })
export const shipmentRepository = genRepo('shipments', { tenantId: 'tenant_id', shipmentNumber: 'shipment_number', packingListId: 'packing_list_id', packingNumber: 'packing_number', soId: 'so_id', soNumber: 'so_number', warehouseId: 'warehouse_id', warehouseName: 'warehouse_name', customerId: 'customer_id', customerName: 'customer_name', shipToAddress: 'ship_to_address', shipToCity: 'ship_to_city', shipToState: 'ship_to_state', transporterName: 'transporter_name', vehicleNumber: 'vehicle_number', driverName: 'driver_name', driverMobile: 'driver_mobile', lrNumber: 'lr_number', lrDate: 'lr_date', ewayBillNumber: 'eway_bill_number', ewayBillDate: 'eway_bill_date', totalQty: 'total_qty', totalWeight: 'total_weight', totalVolume: 'total_volume', boxCount: 'box_count', freightAmount: 'freight_amount', freightPaidBy: 'freight_paid_by', shippingLabelUrl: 'shipping_label_url', trackingNumber: 'tracking_number', dispatchedBy: 'dispatched_by', dispatchedByName: 'dispatched_by_name', dispatchedAt: 'dispatched_at', status: 'status', remarks: 'remarks' })
export async function genPickNumber(t: string): Promise<string> { const y = new Date().getFullYear(); const c = await query<{ cnt: string }>(`SELECT COUNT(*) as cnt FROM pick_lists WHERE tenant_id = $1 AND pick_number LIKE 'PICK-${y}-%'`, [t]); return `PICK-${y}-${String(Number(c.rows[0]!.cnt) + 1).padStart(6, '0')}` }
export async function genPackNumber(t: string): Promise<string> { const y = new Date().getFullYear(); const c = await query<{ cnt: string }>(`SELECT COUNT(*) as cnt FROM packing_lists WHERE tenant_id = $1 AND packing_number LIKE 'PACK-${y}-%'`, [t]); return `PACK-${y}-${String(Number(c.rows[0]!.cnt) + 1).padStart(6, '0')}` }
export async function genShipNumber(t: string): Promise<string> { const y = new Date().getFullYear(); const c = await query<{ cnt: string }>(`SELECT COUNT(*) as cnt FROM shipments WHERE tenant_id = $1 AND shipment_number LIKE 'SHIP-${y}-%'`, [t]); return `SHIP-${y}-${String(Number(c.rows[0]!.cnt) + 1).padStart(6, '0')}` }
