import { Hono } from 'hono'
import { z } from 'zod'
import { zValidator } from '@hono/zod-validator'
import { success, paginated } from '@/core/response'
import { requirePermission } from '@/middleware/rbac'
import { Permission } from '@/core/permissions'
import { deliveryManagementService } from '../service'
export const deliveryManagementRoutes = new Hono()
const CR = Permission.DELIVERY_READ
const CU = Permission.DELIVERY_CREATE
const doSchema = z.object({ shipmentId: z.string().uuid(), shipmentNumber: z.string().min(1), soId: z.string().uuid().optional(), soNumber: z.string().optional(), customerId: z.string().uuid().optional(), customerName: z.string().optional(), deliveryAddress: z.string().optional(), deliveryCity: z.string().optional(), deliveryState: z.string().optional(), deliveryPincode: z.string().optional(), deliveryContact: z.string().optional(), deliveryPhone: z.string().optional(), scheduledDate: z.string().datetime().optional(), totalQty: z.number().positive().optional(), totalWeight: z.number().positive().optional(), driverName: z.string().optional(), driverMobile: z.string().optional(), vehicleNumber: z.string().optional(), deliveryType: z.string().default('STANDARD') })
const podSchema = z.object({ deliveryOrderId: z.string().uuid(), deliveryNumber: z.string().optional(), receivedBy: z.string().optional(), receivedByName: z.string().optional(), receivedByDesignation: z.string().optional(), customerSignature: z.string().optional(), signatureImageUrl: z.string().optional(), gpsLatitude: z.number().optional(), gpsLongitude: z.number().optional(), gpsTimestamp: z.string().datetime().optional(), deliveryPhotoUrl: z.string().optional(), deliveredQty: z.number().positive(), damagedQty: z.number().nonnegative().default(0), shortQty: z.number().nonnegative().default(0), deliveryStatus: z.enum(['DELIVERED', 'PARTIAL', 'FAILED', 'RESCHEDULED']).default('DELIVERED'), customerRemarks: z.string().optional(), driverRemarks: z.string().optional() })
const excSchema = z.object({ deliveryOrderId: z.string().uuid(), deliveryNumber: z.string().optional(), exceptionType: z.string().min(1), exceptionReason: z.string().min(1), rescheduledDate: z.string().datetime().optional(), rescheduleReason: z.string().optional() })
deliveryManagementRoutes.get('/delivery-orders', requirePermission(CR), async (c) => { const r = await deliveryManagementService.listDeliveryOrders({ page: Number(c.req.query('page') ?? 1), pageSize: Number(c.req.query('pageSize') ?? 25), status: c.req.query('status') ?? undefined }); return c.json(paginated(r.rows, { correlationId: c.req.header('X-Request-Id') ?? '', page: r.page, pageSize: r.pageSize, total: r.total })) })
deliveryManagementRoutes.post('/delivery-orders', requirePermission(CU), zValidator('json', doSchema), async (c) => { const b = c.req.valid('json' as never) as z.infer<typeof doSchema>; const d = await deliveryManagementService.createDeliveryOrder(b); return c.json(success(d, { message: 'Delivery order created' }), 201) })
deliveryManagementRoutes.get('/pods', requirePermission(CR), async (c) => { const r = await deliveryManagementService.listPods({ page: Number(c.req.query('page') ?? 1), pageSize: Number(c.req.query('pageSize') ?? 25) }); return c.json(paginated(r.rows, { correlationId: c.req.header('X-Request-Id') ?? '', page: r.page, pageSize: r.pageSize, total: r.total })) })
deliveryManagementRoutes.post('/pods', requirePermission(CU), zValidator('json', podSchema), async (c) => { const b = c.req.valid('json' as never) as z.infer<typeof podSchema>; const p = await deliveryManagementService.createPod(b); return c.json(success(p, { message: 'Proof of delivery recorded' }), 201) })
deliveryManagementRoutes.get('/exceptions', requirePermission(CR), async (c) => { const r = await deliveryManagementService.listExceptions({ page: Number(c.req.query('page') ?? 1), pageSize: Number(c.req.query('pageSize') ?? 25), status: c.req.query('status') ?? undefined }); return c.json(paginated(r.rows, { correlationId: c.req.header('X-Request-Id') ?? '', page: r.page, pageSize: r.pageSize, total: r.total })) })
deliveryManagementRoutes.post('/exceptions', requirePermission(CU), zValidator('json', excSchema), async (c) => { const b = c.req.valid('json' as never) as z.infer<typeof excSchema>; const e = await deliveryManagementService.createException(b); return c.json(success(e, { message: 'Exception recorded' }), 201) })
