import { Hono } from 'hono'
import { z } from 'zod'
import { zValidator } from '@hono/zod-validator'
import { success, paginated } from '@/core/response'
import { requirePermission } from '@/middleware/rbac'
import { Permission } from '@/core/permissions'
import { pickPackDispatchService } from '../service'
export const pickPackDispatchRoutes = new Hono()
const CR = Permission.CUSTOMER_READ
const CU = Permission.CUSTOMER_UPDATE
const pickSchema = z.object({ waveId: z.string().uuid().optional(), waveNumber: z.string().optional(), warehouseId: z.string().uuid(), warehouseName: z.string().min(1), pickerId: z.string().uuid().optional(), pickerName: z.string().optional(), soIds: z.array(z.string().uuid()).min(1) })
const packSchema = z.object({ pickListId: z.string().uuid().optional(), pickNumber: z.string().optional(), warehouseId: z.string().uuid(), warehouseName: z.string().min(1), packerId: z.string().uuid().optional(), packerName: z.string().optional(), totalLines: z.number().int().positive(), totalQty: z.number().positive() })
const shipSchema = z.object({ packingListId: z.string().uuid().optional(), packingNumber: z.string().optional(), soId: z.string().uuid().optional(), soNumber: z.string().optional(), warehouseId: z.string().uuid(), warehouseName: z.string().min(1), customerId: z.string().uuid().optional(), customerName: z.string().optional(), shipToAddress: z.string().optional(), shipToCity: z.string().optional(), shipToState: z.string().optional(), transporterName: z.string().optional(), vehicleNumber: z.string().optional(), driverName: z.string().optional(), driverMobile: z.string().optional(), lrNumber: z.string().optional(), totalQty: z.number().positive().optional(), totalWeight: z.number().positive().optional(), boxCount: z.number().int().positive().optional(), freightAmount: z.number().nonnegative().optional(), freightPaidBy: z.string().default('CUSTOMER') })
pickPackDispatchRoutes.get('/pick-lists', requirePermission(CR), async (c) => { const r = await pickPackDispatchService.listPickLists({ page: Number(c.req.query('page') ?? 1), pageSize: Number(c.req.query('pageSize') ?? 25), status: c.req.query('status') ?? undefined }); return c.json(paginated(r.rows, { correlationId: c.req.header('X-Request-Id') ?? '', page: r.page, pageSize: r.pageSize, total: r.total })) })
pickPackDispatchRoutes.post('/pick-lists', requirePermission(CU), zValidator('json', pickSchema), async (c) => { const b = c.req.valid('json' as never) as z.infer<typeof pickSchema>; const p = await pickPackDispatchService.createPickList(b); return c.json(success(p, { message: 'Pick list created' }), 201) })
pickPackDispatchRoutes.get('/packing-lists', requirePermission(CR), async (c) => { const r = await pickPackDispatchService.listPackingLists({ page: Number(c.req.query('page') ?? 1), pageSize: Number(c.req.query('pageSize') ?? 25), status: c.req.query('status') ?? undefined }); return c.json(paginated(r.rows, { correlationId: c.req.header('X-Request-Id') ?? '', page: r.page, pageSize: r.pageSize, total: r.total })) })
pickPackDispatchRoutes.post('/packing-lists', requirePermission(CU), zValidator('json', packSchema), async (c) => { const b = c.req.valid('json' as never) as z.infer<typeof packSchema>; const p = await pickPackDispatchService.createPackingList(b); return c.json(success(p, { message: 'Packing list created' }), 201) })
pickPackDispatchRoutes.get('/shipments', requirePermission(CR), async (c) => { const r = await pickPackDispatchService.listShipments({ page: Number(c.req.query('page') ?? 1), pageSize: Number(c.req.query('pageSize') ?? 25), status: c.req.query('status') ?? undefined }); return c.json(paginated(r.rows, { correlationId: c.req.header('X-Request-Id') ?? '', page: r.page, pageSize: r.pageSize, total: r.total })) })
pickPackDispatchRoutes.post('/shipments', requirePermission(CU), zValidator('json', shipSchema), async (c) => { const b = c.req.valid('json' as never) as z.infer<typeof shipSchema>; const s = await pickPackDispatchService.createShipment(b); return c.json(success(s, { message: 'Shipment created' }), 201) })
