import { query } from '@/core/db/pglite'
import { randomUUID } from 'node:crypto'
function genRepo(table: string, fields: Record<string, string>) {
  return {
    async create(data: Record<string, unknown>) { const id = randomUUID(); const cols = ['id']; const vals: unknown[] = [id]; for (const [k, c] of Object.entries(fields)) { if (data[k] !== undefined && data[k] !== null) { cols.push(c); vals.push(data[k]) } } const ph = vals.map((_, i) => `\$${i + 1}`).join(', '); await query(`INSERT INTO ${table} (${cols.join(', ')}, created_at, updated_at) VALUES (${ph}, NOW(), NOW())`, vals); const r = await query(`SELECT * FROM ${table} WHERE id = $1`, [id]); return r.rows[0] ?? null },
    async findById(t: string, id: string) { const r = await query(`SELECT * FROM ${table} WHERE tenant_id = $1 AND id = $2 AND deleted_at IS NULL`, [t, id]); return r.rows[0] ?? null },
    async list(t: string, p: { page?: number; pageSize?: number; status?: string } = {}) { const pg = p.page ?? 1; const ps = p.pageSize ?? 25; const off = (pg - 1) * ps; let w = 'tenant_id = $1 AND deleted_at IS NULL'; const sp: unknown[] = [t]; let i = 2; if (p.status) { w += ` AND status = $${i++}`; sp.push(p.status) } const c = await query<{ cnt: string }>(`SELECT COUNT(*) as cnt FROM ${table} WHERE ${w}`, sp); const r = await query(`SELECT * FROM ${table} WHERE ${w} ORDER BY created_at DESC LIMIT $${i} OFFSET $${i + 1}`, [...sp, ps, off]); return { rows: r.rows, total: Number(c.rows[0]!.cnt), page: pg, pageSize: ps } },
  }
}
export const deliveryOrderRepository = genRepo('delivery_orders', { tenantId: 'tenant_id', deliveryNumber: 'delivery_number', shipmentId: 'shipment_id', shipmentNumber: 'shipment_number', soId: 'so_id', soNumber: 'so_number', customerId: 'customer_id', customerName: 'customer_name', deliveryAddress: 'delivery_address', deliveryCity: 'delivery_city', deliveryState: 'delivery_state', deliveryPincode: 'delivery_pincode', deliveryContact: 'delivery_contact', deliveryPhone: 'delivery_phone', scheduledDate: 'scheduled_date', estimatedArrival: 'estimated_arrival', actualArrival: 'actual_arrival', departureTime: 'departure_time', totalQty: 'total_qty', totalWeight: 'total_weight', driverName: 'driver_name', driverMobile: 'driver_mobile', vehicleNumber: 'vehicle_number', deliveryType: 'delivery_type', status: 'status', remarks: 'remarks' })
export const proofOfDeliveryRepository = genRepo('proof_of_deliveries', { tenantId: 'tenant_id', deliveryOrderId: 'delivery_order_id', deliveryNumber: 'delivery_number', receivedBy: 'received_by', receivedByName: 'received_by_name', receivedByDesignation: 'received_by_designation', customerSignature: 'customer_signature', signatureImageUrl: 'signature_image_url', gpsLatitude: 'gps_latitude', gpsLongitude: 'gps_longitude', gpsTimestamp: 'gps_timestamp', deliveryPhotoUrl: 'delivery_photo_url', deliveredQty: 'delivered_qty', damagedQty: 'damaged_qty', shortQty: 'short_qty', deliveryStatus: 'delivery_status', customerRemarks: 'customer_remarks', driverRemarks: 'driver_remarks', confirmedBy: 'confirmed_by', confirmedByName: 'confirmed_by_name', confirmedAt: 'confirmed_at' })
export const deliveryExceptionRepository = genRepo('delivery_exceptions', { tenantId: 'tenant_id', deliveryOrderId: 'delivery_order_id', deliveryNumber: 'delivery_number', exceptionType: 'exception_type', exceptionReason: 'exception_reason', rescheduledDate: 'rescheduled_date', rescheduleReason: 'reschedule_reason', reportedBy: 'reported_by', reportedByName: 'reported_by_name', status: 'status', resolution: 'resolution', resolvedBy: 'resolved_by', resolvedByName: 'resolved_by_name', resolvedAt: 'resolved_at', remarks: 'remarks' })
export async function genDeliverNumber(t: string): Promise<string> { const y = new Date().getFullYear(); const c = await query<{ cnt: string }>(`SELECT COUNT(*) as cnt FROM delivery_orders WHERE tenant_id = $1 AND delivery_number LIKE 'DEL-${y}-%'`, [t]); return `DEL-${y}-${String(Number(c.rows[0]!.cnt) + 1).padStart(6, '0')}` }
