apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "suop.fullname" . }}-config
  labels:
    {{- include "suop.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.backend.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
